// Country codes mapped to Clearbit country values

exports.main = async (event, callback) => {

    var countryCode = event.inputFields['country_code'];
    
    const countries = {
        dk: "Denmark",
        gb: "United Kingdom",
        us: "United States",
        de: "Germany",
        se: "Sweden",
        nl: "Netherlands",
        it: "Italy",
        in: "India",
        no: "Norway",
        fr: "France",
        es: "Spain",
        fi: "Finland",
        pl: "Poland",
        be: "Belgium",
        ro: "Romania",
        ca: "Canada",
        ch: "Switzerland",
        ie: "Ireland",
        za: "South Africa",
        pt: "Portugal",
        br: "Brazil",
        uk: "United Kingdom",
        au: "Australia",
        lt: "Lithuania",
        tn: "Tunisia",
        ua: "Ukraine",
        at: "Austria",
        ph: "Philippines",
        vn: "Vietnam",
        sg: "Singapore",
        ru: "Russia",
        mx: "Mexico",
        gr: "Greece",
        pk: "Pakistan",
        cn: "China",
        id: "Indonesia",
        lv: "Latvia",
        ae: "United Arab Emirates",
        tr: "Turkey",
        il: "Israel",
        hu: "Hungary",
        ee: "Estonia",
        bg: "Bulgaria",
        co: "Colombia",
        cz: "Czech Republic",
        my: "Malaysia",
        ng: "Nigeria",
        th: "Thailand",
        hr: "Croatia",
        hk: "Hong Kong",
        ma: "Morocco",
        sk: "Slovakia",
        rs: "Serbia",
        gl: "Greenland",
        rw: "Rwanda",
        np: "Nepal",
        jp: "Japan",
        by: "Belarus",
        sa: "Saudi Arabia",
        is: "Iceland",
        fo: "Faroe Islands",
        lb: "Lebanon",
        eg: "Egypt",
        si: "Slovenia",
        sw: "Sweden",
        ar: "Argentina",
        ke: "Kenya",
        sn: "Senegal",
        bd: "Bangladesh",
        en: "Estonia",
        kr: "Korea, Republic of",
        lu: "Luxembourg",
        nz: "New Zealand",
        ir: "Iran, Islamic Republic of",
        mt: "Malta",
        mk: "Macedonia, the former Yugoslav Republic of",
        lk: "Sri Lanka",
        md: "Moldova, Republic of",
        cl: "Chile",
        ci: "Cote d'Ivoire",
        al: "Albania",
        gt: "Guatemala",
        tw: "Taiwan",
        cy: "Cyprus",
        ba: "Bosnia and Herzegovina",
        dz: "Algeria",
        gh: "Ghana",
        af: "Afghanistan",
        ge: "Georgia",
        jo: "Jordan",
        tt: "Trinidad and Tobago",
        az: "Azerbaijan",
        cm: "Cameroon",
        ug: "Uganda",
        xk: "Kosovo",
        kw: "Kuwait",
        pe: "Peru",
        jm: "Jamaica",
        ve: "Venezuela, Bolivarian Republic of",
        iq: "Iraq",
        am: "Armenia",
        bs: "Bahamas",
        bh: "Bahrain",
        qa: "Qatar",
        do: "Dominican Republic",
        ec: "Ecuador",
        tz: "Tanzania, the United Republic of",
        bw: "Botswana",
        cr: "Costa Rica",
        kh: "Cambodia",
        me: "Montenegro",
        mq: "Martinique",
        pa: "Panama",
        mu: "Mauritius",
        mv: "Maldives",
        zw: "Zimbabwe",
        cu: "Cuba",
        mc: "Monaco",
        ml: "Mali",
        mm: "Myanmar",
        mn: "Mongolia",
        om: "Oman",
        uy: "Uruguay",
        ad: "Andorra",
        bj: "Benin",
        et: "Ethiopia",
        ht: "Haiti",
        pr: "Puerto Rico",
        ps: "Palestine",
        tg: "Togo",
        bb: "Barbados",
        bo: "Bolivia, Plurinational State of",
        gn: "Guinea",
        kz: "Kazakhstan",
        so: "Somalia",
        tc: "Turks and Caicos Islands",
        bf: "Burkina Faso",
        cd: "Congo, the Democratic Republic of the",
        cw: "Curaçao",
        dm: "Dominica",
        gg: "Guernsey",
        gi: "Gibraltar",
        hn: "Honduras",
        je: "Jersey",
        na: "Namibia",
        pg: "Papua New Guinea",
        re: "Reunion",
        uz: "Uzbekistan",
        bm: "Bermuda",
        bz: "Belize",
        cg: "Congo",
        cv: "Cape Verde",
        ga: "Gabon",
        gm: "Gambia",
        gw: "Guinea-Bissau",
        kg: "Kyrgyzstan",
        ls: "Lesotho",
        mg: "Madagascar",
        nc: "New Caledonia",
        ne: "Niger",
        ni: "Nicaragua",
        ss: "South Sudan",
        sv: "El Salvador",
        sx: "Sint Maarten",
        sy: "Syrian Arab Republic",
        ag: "Antigua and Barbuda",
        ao: "Angola",
        bi: "Burundi",
        bn: "Brunei Durussalam",
        cf: "Central African Republic",
        da: "Denmark",
        gp: "Guadeloupe",
        gu: "Guam",
        ic: "Iceland",
        im: "Isle of Man",
        la: "Lao People's Democratic Republic",
        li: "Liechtenstein",
        lr: "Liberia",
        ly: "Libya",
        mo: "Macao",
        mw: "Malawi",
        mz: "Mozambique",
        sc: "Seychelles",
        sd: "Sudan",
        sr: "Suriname",
        sz: "Eswatini",
        tm: "Turkmenistan",
        tv: "Tuvalu",
        vu: "Vanuatu",
        ye: "Yemen",
        zm: "Zambia",
        ax: "Aland Islands",
        as: "American Samoa",
        ai: "Anguilla",
        aq: "Antarctica",
        aw: "Aruba",
        bt: "Bhutan",
        bq: "Bonaire, Sint Eustatius and Saba",
        io: "British Indian Ocean Territory",
        ky: "Cayman Islands",
        td: "Chad",
        cc: "Cocos (Keeling) Islands",
        km: "Comoros",
        ck: "Cook Islands",
        dj: "Djibouti",
        gq: "Equatorial Guinea",
        er: "Eritrea",
        fk: "Falkland Islands (Malvinas)",
        fj: "Fiji",
        gf: "French Guiana",
        pf: "French Polynesia",
        gd: "Grenada",
        gy: "Guyana",
        va: "Holy See",
        ki: "Kiribati",
        kp: "Korea, Democratic People's Republic of",
        mh: "Marshall Islands",
        mr: "Mauritania",
        yt: "Mayotte",
        fm: "Micronesia (Federated States of)",
        ms: "Montserrat",
        nr: "Nauru",
        nu: "Niue",
        nf: "Norfolk Island",
        mp: "Northern Mariana Islands",
        pw: "Palau",
        py: "Paraguay",
        pn: "Pitcairn",
        bl: "Saint Barthélemy",
        sh: "Saint Helena, Ascension and Tristan da Cunha",
        kn: "Saint Kitts and Nevis",
        lc: "Saint Lucia",
        mf: "Saint Martin (French part)",
        pm: "Saint Pierre and Miquelon",
        vc: "Saint Vincent and the Grenadines",
        ws: "Samoa",
        sm: "San Marino",
        st: "Sao Tome and Principe",
        sl: "Sierra Leone",
        sb: "Solomon Islands",
        sj: "Svalbard and Jan Mayen",
        tj: "Tajikistan",
        tl: "Timor-Leste",
        to: "Tonga",
        vi: "Virgin Islands (U.S.)",
        vg: "Virgin Islands, British",
        wf: "Wallis and Futuna"
        };
 
    callback({
        outputFields:{
            countryOutput: countries[countryCode]
        }
          })
  }